# database-crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # Name format: <plural>.<group>
  name: databases.mycompany.io
spec:
  # API group for your custom resource
  group: mycompany.io
  
  # Can be Namespaced or Cluster
  scope: Namespaced
  
  # Different names for your resource
  names:
    plural: databases     # Used in API URLs
    singular: database    # Used in kubectl output
    kind: Database        # Used in YAML files
    shortNames: ["db"]    # Short name for kubectl
  
  # API versions
  versions:
  - name: v1
    served: true    # API server will serve this version
    storage: true   # This version is stored in etcd
    
    # Define the structure of your custom resource
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required: ["engine", "version"]  # These fields are mandatory
            properties:
              # Database engine type
              engine:
                type: string
                enum: ["mysql", "postgresql", "mongodb"]
                description: "Database engine type"
              
              # Database version
              version:
                type: string
                description: "Database version (e.g., 8.0, 13.2)"
              
              # Storage size (optional)
              storageSize:
                type: string
                default: "10Gi"
                description: "Storage size (e.g., 10Gi, 100Gi)"
              
              # Number of replicas (optional)
              replicas:
                type: integer
                minimum: 1
                maximum: 5
                default: 1
                description: "Number of database replicas"
          
          # Status is managed by controllers
          status:
            type: object
            properties:
              # Current state
              phase:
                type: string
                enum: ["Pending", "Running", "Failed"]
              
              # Database connection info
              connectionString:
                type: string
    
    # Custom columns for kubectl output
    additionalPrinterColumns:
    - name: Engine
      type: string
      jsonPath: .spec.engine
    - name: Version
      type: string
      jsonPath: .spec.version
    - name: Storage
      type: string
      jsonPath: .spec.storageSize
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
