apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: lbl
            operator: In
            values:
            - tea          
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent

