apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      tolerations:
        - key: "worker"
          operator: "Equal"
          value: "1"
          effect: "NoSchedule"
      containers:
        - name: nginx-container
          image: nginx
