apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  initContainers:
  - name: check-env
    image: busybox
    env:
    - name: EXPECTED_VALUE
      value: "production"
    - name: CURRENT_VALUE
      value: "production1"
    command: ['sh', '-c']
    args:
    - |
      echo "Starting value comparison..."
      echo "Expected value: $EXPECTED_VALUE"
      echo "Current value: $CURRENT_VALUE"

      if [ "$EXPECTED_VALUE" = "$CURRENT_VALUE" ]; then
        echo "Values match! Validation successful."
        echo "Sleeping for 15 seconds..."
        sleep 15
        echo "Init container completed successfully!"
        exit 0
      else
        echo "Values do not match! Validation failed."
        echo "Expected: $EXPECTED_VALUE"
        echo "Got: $CURRENT_VALUE"
        exit 1
      fi
  containers:
  - name: main-app
    image: nginx:latest
